"""Change_failure_reason_to_JSONB

Revision ID: 2dce8252d1bd
Revises: 5907acb05fd2
Create Date: 2026-02-07 21:11:10.082761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dce8252d1bd'
down_revision: Union[str, Sequence[str], None] = '5907acb05fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications', 'failure_reason',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               postgresql_using="jsonb_build_object('message', failure_reason)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications', 'failure_reason',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
