"""Add_quality_and_authenticity_metrics

Revision ID: 5907acb05fd2
Revises: c05ac553066a
Create Date: 2026-02-07 21:06:36.795178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5907acb05fd2'
down_revision: Union[str, Sequence[str], None] = 'c05ac553066a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('image_quality_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('verifications', sa.Column('authenticity_checks', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'authenticity_checks')
    op.drop_column('verifications', 'image_quality_metrics')
    # ### end Alembic commands ###
