"""Initial tables

Revision ID: c05ac553066a
Revises: 
Create Date: 2026-02-06 13:43:55.628191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c05ac553066a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('full_name_arabic', sa.String(length=255), nullable=True),
    sa.Column('full_name_english', sa.String(length=255), nullable=True),
    sa.Column('ocr_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('front_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('back_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_ocr_data', 'documents', ['ocr_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_type_number', 'documents', ['document_type', 'document_number'], unique=False)
    op.create_index(op.f('ix_documents_full_name_arabic'), 'documents', ['full_name_arabic'], unique=False)
    op.create_index(op.f('ix_documents_full_name_english'), 'documents', ['full_name_english'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('selfie_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('liveness_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_full_name_english'), table_name='documents')
    op.drop_index(op.f('ix_documents_full_name_arabic'), table_name='documents')
    op.drop_index('idx_documents_type_number', table_name='documents')
    op.drop_index('idx_documents_ocr_data', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
