"""add_transaction_id_column

Revision ID: fadc8e0b8950
Revises: 2dce8252d1bd
Create Date: 2026-02-09 13:43:06.944937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadc8e0b8950'
down_revision: Union[str, Sequence[str], None] = '2dce8252d1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_transaction_id'), 'documents', ['transaction_id'], unique=False)
    op.add_column('verifications', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_verifications_transaction_id'), 'verifications', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_transaction_id'), table_name='verifications')
    op.drop_column('verifications', 'transaction_id')
    op.drop_index(op.f('ix_documents_transaction_id'), table_name='documents')
    op.drop_column('documents', 'transaction_id')
    # ### end Alembic commands ###
