"""
API V1 Schemas for Contract-Compliant Endpoints

These schemas define the exact request/response structure required
by the vendor API contracts.
"""
from typing import Optional, List, Literal
from pydantic import BaseModel, Field, ConfigDict


# =============================================================================
# Base Configuration - All models use camelCase aliases
# =============================================================================

class BaseSchema(BaseModel):
    """Base model with populate_by_name enabled."""
    model_config = ConfigDict(
        populate_by_name=True,
    )


# =============================================================================
# Shared Enums/Types
# =============================================================================

DocumentType = Literal["NATIONAL_ID", "PASSPORT"]
MatchResult = Literal["MATCH", "MISMATCH", "NOT_AVAILABLE"]
AuthenticityStatus = Literal["VALID", "SUSPICIOUS", "INVALID"]
FaceMatchStatusEnum = Literal["MATCH", "NO_MATCH", "INCONCLUSIVE"]
LivenessResult = Literal["LIVE", "NOT_LIVE"]


# =============================================================================
# API 1: OCR Check - Request/Response Models
# =============================================================================

class OCRCheckMetadata(BaseSchema):
    """Metadata for OCR check request."""
    transaction_id: str = Field(..., alias="transactionId", description="Generated by ONECASH Orchestrator")
    document_type: DocumentType = Field(..., alias="documentType", description="NATIONAL_ID | PASSPORT")
    country_code: str = Field(..., alias="countryCode", description="ISO-2/3 country code")


class OCRCheckUserData(BaseSchema):
    """User-entered KYC data for comparison against OCR results."""
    # Name fields (can be Latin or Arabic)
    first_name: str = Field(..., alias="firstName", description="First name (Latin or Arabic)")
    second_name: str = Field(..., alias="secondName", description="Second name (Latin or Arabic)")
    third_name: str = Field(..., alias="thirdName", description="Third name (Latin or Arabic)")
    family_name: str = Field(..., alias="familyName", description="Family name (Latin or Arabic)")
    full_name: str = Field(..., alias="fullName", description="Full name (Yemen IDs may have 5 names)")
    
    # Document fields
    document_number: Optional[str] = Field(None, alias="documentNumber", description="ID/Passport number")
    document_issue_date: Optional[str] = Field(None, alias="documentIssueDate", description="Document issue date")
    document_expiry_date: Optional[str] = Field(None, alias="documentExpiryDate", description="Document expiry date")
    date_of_birth: Optional[str] = Field(None, alias="dateOfBirth", description="Date of birth")
    gender: Optional[Literal["M", "F"]] = Field(None, alias="gender", description="Gender (M/F)")
    
    # Location fields
    city: Optional[str] = Field(None, alias="city", description="City")
    province: Optional[str] = Field(None, alias="province", description="Province")


class OCRFieldData(BaseSchema):
    """Individual OCR field with value and confidence."""
    value: Optional[str] = Field(None, alias="value", description="Extracted value")
    confidence: float = Field(0.0, alias="confidence", ge=0.0, le=1.0, description="Field-level confidence")


class OCRData(BaseSchema):
    """Data extracted from OCR with field-level confidence scores."""
    first_name: Optional[OCRFieldData] = Field(None, alias="firstName")
    second_name: Optional[OCRFieldData] = Field(None, alias="secondName")
    third_name: Optional[OCRFieldData] = Field(None, alias="thirdName")
    family_name: Optional[OCRFieldData] = Field(None, alias="familyName")
    full_name: Optional[OCRFieldData] = Field(None, alias="fullName")
    document_number: Optional[OCRFieldData] = Field(None, alias="documentNumber")
    document_issue_date: Optional[OCRFieldData] = Field(None, alias="documentIssueDate")
    document_expiry_date: Optional[OCRFieldData] = Field(None, alias="documentExpiryDate")
    date_of_birth: Optional[OCRFieldData] = Field(None, alias="dateOfBirth")
    gender: Optional[OCRFieldData] = Field(None, alias="gender")
    city: Optional[OCRFieldData] = Field(None, alias="city")
    province: Optional[OCRFieldData] = Field(None, alias="province")


class DataComparisonItem(BaseSchema):
    """Individual field comparison result."""
    field_name: str = Field(..., alias="fieldName", description="Field name")
    user_entered_value: Optional[str] = Field(None, alias="userEnteredValue", description="Value provided by user")
    ocr_extracted_value: Optional[str] = Field(None, alias="ocrExtractedValue", description="Value extracted by OCR")
    match_result: MatchResult = Field(..., alias="matchResult", description="MATCH | MISMATCH | NOT_AVAILABLE")


class DocumentAuthenticity(BaseSchema):
    """Document authenticity assessment."""
    score: float = Field(..., alias="score", ge=0.0, le=1.0, description="Authenticity score")
    status: AuthenticityStatus = Field(..., alias="status", description="VALID | SUSPICIOUS | INVALID")


class ImageQualityItem(BaseSchema):
    """Quality assessment for a single image."""
    score: float = Field(..., alias="score", ge=0.0, le=1.0, description="Quality score")
    failure_reasons: List[str] = Field(default_factory=list, alias="failureReasons", description="List of issues")


class ImageQuality(BaseSchema):
    """Image quality assessment for all images."""
    front_image: Optional[ImageQualityItem] = Field(None, alias="frontImage")
    back_image: Optional[ImageQualityItem] = Field(None, alias="backImage")


class DocumentVerificationScore(BaseSchema):
    """Detailed breakdown of document verification score (max 35 pts)."""
    authenticity: float = Field(0.0, alias="authenticity", ge=0.0, le=10.0, description="Document authenticity score (max 10)")
    quality: float = Field(0.0, alias="quality", ge=0.0, le=10.0, description="Image quality score (max 10)")
    ocr_confidence: float = Field(0.0, alias="ocrConfidence", ge=0.0, le=10.0, description="OCR confidence score (max 10)")
    front_back_match: float = Field(0.0, alias="frontBackMatch", ge=0.0, le=5.0, description="Front/back ID match (max 5, National ID only)")
    total: float = Field(0.0, alias="total", ge=0.0, le=35.0, description="Total document verification score")


class DataMatchScore(BaseSchema):
    """Detailed breakdown of data matching score (max 30 pts)."""
    id_number: float = Field(0.0, alias="idNumber", ge=0.0, le=20.0, description="ID number match score (max 20)")
    name_match: float = Field(0.0, alias="nameMatch", ge=0.0, le=10.0, description="Name match score (max 10)")
    total: float = Field(0.0, alias="total", ge=0.0, le=30.0, description="Total data match score")


class OCRCheckResponse(BaseSchema):
    """Response for OCR Check endpoint (API 1)."""
    transaction_id: str = Field(..., alias="transactionId", description="Unique transaction identifier")
    
    # Transliterated names (flattened)
    transliterated_first_name: Optional[str] = Field(None, alias="transliteratedFirstName")
    transliterated_second_name: Optional[str] = Field(None, alias="transliteratedSecondName")
    transliterated_third_name: Optional[str] = Field(None, alias="transliteratedThirdName")
    transliterated_family_name: Optional[str] = Field(None, alias="transliteratedFamilyName")
    transliterated_full_name: Optional[str] = Field(None, alias="transliteratedFullName")
    
    # OCR extracted data
    ocr_data: OCRData = Field(..., alias="ocrData", description="OCR extracted fields with confidence")
    
    # Data comparison
    data_comparison: List[DataComparisonItem] = Field(
        default_factory=list, alias="dataComparison", description="Field-by-field comparison"
    )
    
    # Document authenticity
    document_authenticity: DocumentAuthenticity = Field(..., alias="documentAuthenticity")
    
    # Image quality
    image_quality: ImageQuality = Field(..., alias="imageQuality")
    
    # Errors (for error handling)
    errors: List[str] = Field(default_factory=list, alias="errors", description="Any errors encountered")
    
    # Scoring breakdown
    document_verification_score: Optional[DocumentVerificationScore] = Field(None, alias="documentVerificationScore")
    data_match_score: Optional[DataMatchScore] = Field(None, alias="dataMatchScore")


# =============================================================================
# API 2: Face Match - Request/Response Models
# =============================================================================

class FaceMatchResult(BaseSchema):
    """Face matching result."""
    score: float = Field(..., alias="score", ge=0.0, le=100.0, description="Match score (0-100)")
    status: FaceMatchStatusEnum = Field(..., alias="status", description="MATCH | NO_MATCH | INCONCLUSIVE")


class LivenessResult_(BaseSchema):
    """Liveness detection result."""
    result: LivenessResult = Field(..., alias="result", description="LIVE | NOT_LIVE")
    confidence_score: float = Field(..., alias="confidenceScore", ge=0.0, le=100.0, description="Liveness confidence")


class SelfieImageQuality(BaseSchema):
    """Image quality for selfie."""
    score: float = Field(..., alias="score", ge=0.0, le=1.0, description="Selfie quality score")
    failure_reasons: List[str] = Field(default_factory=list, alias="failureReasons", description="Quality issues")


class FaceAndLivenessScore(BaseSchema):
    """Detailed breakdown of face and liveness score (max 35 pts)."""
    face_match: float = Field(0.0, alias="faceMatch", ge=0.0, le=20.0, description="Face match score (max 20)")
    liveness: float = Field(0.0, alias="liveness", ge=0.0, le=15.0, description="Liveness score (max 15)")
    total: float = Field(0.0, alias="total", ge=0.0, le=35.0, description="Total face and liveness score")


class FaceMatchResponse(BaseSchema):
    """Response for Face Match endpoint (API 2)."""
    transaction_id: str = Field(..., alias="transactionId", description="Unique transaction identifier")
    
    # Face matching
    face_match: FaceMatchResult = Field(..., alias="faceMatch", description="Face matching result")
    
    # Liveness
    liveness: LivenessResult_ = Field(..., alias="liveness", description="Liveness detection result")
    
    # Image quality
    image_quality: SelfieImageQuality = Field(..., alias="imageQuality", description="Selfie quality")
    
    # Final score (based on OCR + Face matching, linked by transactionId)
    final_score: float = Field(..., alias="finalScore", ge=0.0, le=100.0, description="Combined final score")
    
    # Errors
    errors: List[str] = Field(default_factory=list, alias="errors", description="Any errors encountered")
    
    # Scoring breakdown
    face_and_liveness_score: Optional[FaceAndLivenessScore] = Field(None, alias="faceAndLivenessScore")
